# import required libraries
from snakemake.utils import min_version


##### set minimum snakemake version #####
min_version("8.4.1")


containerized: "docker://ghcr.io/ht-diva/pqtl_pipeline_finemap:44f3df5"


# read the configuration file
configfile: "conf/config.yaml"
config_copy = "conf/config.yaml"


include: "rules/common.smk"
include: "rules/locus_breaker.smk"
include: "rules/cojo.smk"
include: "rules/coloc.smk"
include: "rules/return_config.smk"


if config.get("run_coloc"):
    rule all:
        input:
            rules.collect_loci.output[0],
            rules.collect_conditionals.output.ofile,
            expand(ws_path("coloc/chr{chr_cs}_colocalization.table.all.tsv"), chr_cs = range(1,23)),
            ws_path("config/config_used.yaml")

else:
    rule all:
        input:
            rules.collect_loci.output[0],
            rules.collect_conditionals.output.ofile,
            ws_path("config/config_used.yaml")
