# import required libraries
from snakemake.utils import min_version


##### set minimum snakemake version #####
min_version("8.4.1")


containerized: "docker://ghcr.io/ht-diva/pqtl_pipeline_finemap:ee49bec"


# read the configuration file
configfile: "conf/config_finemap.yaml"


include: "rules/common.smk"
include: "rules/locus_breaker.smk"
include: "rules/cojo.smk"


rule all:
    input:
        expand(ws_path("cojo/{seqid}/sentinel.txt"), seqid=analytes.seqid),
        #expand(ws_path("break/{seqid}_loci.csv"), seqid=analytes.seqid)
        ws_path("break/collected_loci_excluding_mhc.csv"),
