path_code: "workflow/scripts/"
path_geno: "/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/bed/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"

sumstats_path: conf/path_meta_five.txt
workspace_path: "results/meta_std"

labels:
  chr_label: "'##CHR'"
  pos_label: "POS"
  snpid_label: "SNPID"
  ea_label: "EA"
  oa_label: "NEA"
  eaf_label: "EAF"
  beta_label: "BETA"
  se_label: "SE"
  p_label: "MLOG10P"
  n_label: "N"

thresholds:
  p1: 1.256913021618904e-11
  p2: 1e-06
  p_cojo: 1.256913021618904e-11
  p_jumper: 1e-04
  p_signif: 2.513826043237808e-10
  p_limit: 1e-04
  ppp: 0.99
  hole: 250000

NLRP12: 1
build: 37
redefine_region: 0
