path_code: "workflow/scripts/"
path_geno: "/exchange/healthds/pQTL/INTERVAL/Genetic_QC_files/bed/qc_recoded_harmonised/impute_recoded_selected_sample_filter_hq_var_new_id_alleles_"

sumstats_path: conf/path_interval_one.txt
workspace_path: "results/interval_nick"

labels:
  chr_label: "CHROM"
  pos_label: "GENPOS"
  snpid_label: "ID"
  ea_label: "ALLELE1"
  oa_label: "ALLELE0"
  eaf_label: "A1FREQ"
  beta_label: "BETA"
  se_label: "SE"
  p_label: "LOG10P"
  n_label: "N"

thresholds:
  p1: 1.256913021618904e-11
  p2: 1e-06
  p3: 1e-04
  p4: 1.256913021618904e-11
  ppp: 0.99
  hole: 250000
