
workspace: "results/meta_hole_3M/"
path_mvp:  "/group/diangelantonio/users/giulia.pontali/file_to_share/unconditional_IVs_from_MVP_for_coloc.txt"

#"/group/diangelantonio/users/giulia.pontali/file_to_share/unconditional_IVs_from_MVP.txt"
