executor: slurm
jobs: 450
software-deployment-method:
   - conda
#   - apptainer
retries: 3

# Cluster submission
jobname: "{jobid}.{rule}"
max-jobs-per-second: 10
max-status-checks-per-second: 1
local-cores: 1
cores: &cores 2
latency-wait: 60
keep-going: True
rerun-incomplete: True
printshellcmds: True
scheduler: ilp

default-resources:
    slurm_partition: cpuq
    #slurm_account: ${USER}
    mem_mb: attempt * 512
    threads: 1
    runtime: attempt * 5

set-resources:
    break_locus:
        mem_mb: 8000 + attempt * 2048
    collect_loci:
        mem_mb: 8000 + attempt * 2048
    run_cojo:
        mem_mb: 8000 + attempt * 2048
        threads: *cores
    collect_credible_sets:
        mem_mb: 8000 + attempt * 2048
        disk_mb: 8000 + attempt * 2048
    master_file:
        mem_mb: 4000 + attempt * 2048
        threads: *cores
    merry_go_round:
        mem_mb: 4000 + attempt * 2048
        threads: *cores
    run_coloc:
        mem_mb: 80000 + attempt * 2048
        disk_mb: 32000 + attempt * 2048
        threads: *cores